config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks

  resources :tips

  resources :services

  get 'about', to: 'pages#about'

  resources :contacts, only: [:new, :create]
  devise_for :users
  root to: 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :services
end

app/models/concerns/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Contact Form",
      :to => "mackenzie@unicasts.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "New Contact",
      :to => "nimrodbahar@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  validates :client, presence: true
  validates :description, presence: true
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :category
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  validates :subject, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  def index
    @feedbacks = Feeback.all
  end

  def show
  end

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(feedback_params)
    if @feedback.save
      redirect_to feedback_path(@feedback), notice: "Feedback was successfully added"
    else
      render action: 'new', notice: "Feedback was not save, please try again"
    end
  end

  def edit
  end

  def update
    @feedack.update(feedback_params)

    redirect_to feedback_path(@feedback)
  end

  def destroy
    @feedback.destroy
  end

  private

  def set_feedback
    @feedback = Feedback.find(params[:id])
  end

  def feedback_params
    params.require(:feedback).permit(:client, :description, :avatar)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @feedbacks = Feedback.all.order(id: :desc).limit(4)
  end

  def about
  end


end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :find_service, except: [:index]
  def index
    if params[:category].blank?
      @services = Service.all.order('created_at ASC')
    else
      @category_id = Category.find_by(name: params[:category]).id
      @services = Service.where(category_id: @category_id).order('created_at ASC')
    end
  end

  def show
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to @service
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def service_params
    params.require(:service).permit(:title, :description)
  end

  def find_service
    @service = Service.find(params[:id])
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  def index
    @tips = Tip.all
  end

  def show

  end

  def new
    @tip = Tip.new
  end

  def create
    @tip = Tip.new(tip_params)
    @tip.save

    redirect_to tip_path(@tip)
  end

  def edit

  end

  def update
    @tip.update(tip_params)

    redirect_to tip_path(@tip)
  end

  def destroy
    @tip.destroy

    redirect_to tips_path, notice: "Your tip has been deleted"
  end

  private

  def set_tip
    @tip = Tip.find(params[:id])
  end

  def tip_params
    params.require(:tip).permit(:subject, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/contacts/create.html.erb
<h1>Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
  <h1>Thank you for your message!</h1>
  <p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<% content_for :navbar do %>
  <%= render 'shared/gennavbar' %>
<% end %>



<div class="skinny_wrapper wrapper_padding">
  <%= form_for @contact do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true %>

    <br>

    <%= f.label :email %><br>
    <%= f.email_field :email, required: true %>

    <br>

    <%= f.label :message %><br>
    <%= f.text_area :message, as: :text %>

    <div class="hidden">
      <%= f.label :nickname %><br>
      <%= f.text_field :nickname, hint: 'leave this field blank' %>
    </div>

    <%= f.submit 'Send Message', class: "button" %>
  <% end %>
</div>

app/views/feedbacks/create.html.erb
<h1>Feedbacks#create</h1>
<p>Find me in app/views/feedbacks/create.html.erb</p>

app/views/feedbacks/destroy.html.erb
<h1>Feedbacks#destroy</h1>
<p>Find me in app/views/feedbacks/destroy.html.erb</p>

app/views/feedbacks/edit.html.erb
<h1>Feedbacks#edit</h1>
<p>Find me in app/views/feedbacks/edit.html.erb</p>

app/views/feedbacks/index.html.erb
<h1>Feedbacks#index</h1>
<p>Find me in app/views/feedbacks/index.html.erb</p>

app/views/feedbacks/new.html.erb
<% content_for :navbar do %>
  <%= render 'shared/gennavbar' %>
<% end %>

<br>

<div class="skinny_wrapper wrapper_padding">
  <%= form_for @feedback, url: feedbacks_path, html: { multipart: true } do |f| %>
    <%= f.label :client %><br>
    <%= f.text_field :client, required: true %>


    <br>

    <%= f.label :description %><br>
    <%= f.text_area :description, required: true %>

    <br>

    <%= f.label :avatar %> <br>
    <%= f.file_field :avatar %>

    <div class="hidden">
      <%= f.label :nickname %><br>
      <%= f.text_field :nickname, hint: 'leave this field blank' %>
    </div>

    <br>

    <%= f.submit 'Create', class: "button" %>

  <% end %>
</div>

app/views/feedbacks/show.html.erb
<%= image_tag @feedback.avatar.url(:medium) %>
<%= @feedback.client %>
<%= @feedback.description  %>

app/views/feedbacks/update.html.erb
<h1>Feedbacks#update</h1>
<p>Find me in app/views/feedbacks/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JenLaw</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <% if content_for? (:navbar) %>
      <%= yield(:navbar) %>
    <% else %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
      </div>
    </footer>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :navbar do %>
  <%= render 'shared/gennavbar' %>
<% end %>

<h2>Hi This is Jennider's about page</h2>

app/views/pages/home.html.erb
<% content_for :navbar do %>
  <%= render 'shared/navbar' %>
<% end %>

<div class="banner">
  <div class="banner-content">
    <h1>Winning with you</h1>
  </div>
</div>


<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="services-card service-hoverable">
        <%=link_to (image_tag "suitcase_yellow.svg"), services_path(category_id: 2) %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="services-card service-hoverable">
        <%=link_to (image_tag "real_estate_yellow.svg"), services_path(category_id: 1) %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="services-card service-hoverable">
        <%=link_to (image_tag "will_small_yellow.svg"), services_path(category_id: 3) %>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <% @feedbacks.each do |feedback|  %>
      <div class="col-xs-12 col-md-6 col-lg-3">
        <div class="feedback-card hoverable">
          <div class="card-up">
              <%= image_tag feedback.avatar.url(:thumb), class: "card-up-client" %>
          </div>
          <div class="card-content">
            <h5><%= feedback.client%></h5>
            <div class="divider-new"></div>
            <p>"<%=feedback.description%>"</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/services/_form.html.erb
<%= simple_form_for(@service, html: { class: 'form-horizontal'}) do |f| %>
  <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category"}, input_html: { class: "dropdown-toggle"} %>
  <%= f.input :title, label: "Service Name", input_html: { class: "form-control"} %>
  <%= f.input :description, label: "Description", input_html: { class: "form-control"} %>
  <br>
  <%= f.button :submit %>
<% end %>

app/views/services/edit.html.erb
<h1>Edit service</h1>
<div class= "container">
  <%= render 'form' %>
</div>


<%= link_to "Back", root_path %>

app/views/services/index.html.erb
<% Category.all.each do |category|  %>
  <li><%= link_to category.name, services_path(category: category.name) %></li>
<% end  %>

app/views/services/new.html.erb
<h1>New service</h1>
<div class= "container">
  <%= render 'form' %>
</div>


<%= link_to "Back", root_path %>

app/views/services/show.html.erb
<h1>This is the service show page</h1>

<h3><%= @service.title %></h3>
<p><%= @service.description %></p>

<%= link_to 'Edit', edit_service_path(@service) %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="site-footer">
  <div class="container">
    <row>
      <div class="footer-links">
        <span class="col-xs-12 col-sm-4"><%= link_to "Contact", new_contact_path %></span>
        <span class="col-xs-12 col-sm-4"><%= link_to "Contact", new_contact_path %></span>
        <span class="col-xs-12 col-sm-4"><%= link_to "Contact", new_contact_path %></span>
      </div>
    </row>
  </div>
</footer>

app/views/shared/_gennavbar.html.erb
<div class="gennavbar-wagon gennavbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "gennavbar-wagon-brand" do %>
    <%= image_tag "logo.svg" %>
  <% end %>
  <!-- Right Navigation -->
  <div class="gennavbar-wagon-right hidden-xs hidden-sm">
    <!-- links -->
    <div class="navbar-wagon-item">
      <%= link_to 'About', about_path, class:"navbar-wagon-link" %>
    </div>
    <div class="navbar-wagon-item">
      <%= link_to 'Tips', tips_path, class:"navbar-wagon-link" %>
    </div>
    <div class="navbar-wagon-item">
      <%= link_to 'Services', services_path, class:"navbar-wagon-link" %>
    </div>
    <div class="navbar-wagon-item">
      <%= link_to 'Contact', new_contact_path, class:"navbar-wagon-link" %>
    </div>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="gennavbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right gennavbar-wagon-dropdown-menu">
        <li><%= link_to 'About', about_path, class:"navbar-wagon-link" %></li>
        <li><%= link_to 'Contact', new_contact_path, class:"gennavbar-wagon-link" %></li>
        <li><%= link_to 'Tips', tips_path, class:"gennavbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.svg" %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- links -->
    <div class="navbar-wagon-item">
      <%= link_to 'About', about_path, class:"navbar-wagon-link" %>
    </div>
    <div class="navbar-wagon-item">
      <%= link_to 'Tips', tips_path, class:"navbar-wagon-link" %>
    </div>
    <div class="navbar-wagon-item">
      <%= link_to 'Services', services_path, class:"navbar-wagon-link" %>
    </div>
    <div class="navbar-wagon-item">
      <%= link_to 'Contact', new_contact_path, class:"navbar-wagon-link" %>
    </div>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to 'About', about_path, class:"navbar-wagon-link" %></li>
        <li><%= link_to 'Contact', new_contact_path, class:"navbar-wagon-link" %></li>
        <li><%= link_to 'Tips', tips_path, class:"navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/tips/_form.html.erb
<%= form_for(@tip) do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/tips/create.html.erb
<h1>Tips#create</h1>
<p>Find me in app/views/tips/create.html.erb</p>

app/views/tips/edit.html.erb
<% content_for :navbar do %>
  <%= render 'shared/gennavbar' %>
<% end %>

<h1>Tips#edit</h1>

<%= render 'form'  %>

app/views/tips/index.html.erb
<% content_for :navbar do %>
  <%= render 'shared/gennavbar' %>
<% end %>

<h1>Tips#index | All the tips</h1>

<h3><%= link_to "New tip", new_tip_path  %></h3>

<% @tips.each do |tip| %>
  <h2><%= tip.subject %></h2>
  <p><%= tip.content %></p>

  <%= link_to "Edit", edit_tip_path(tip) %>
  <%= link_to "Delete", tip_path(tip),
    method: :delete,
    data: { confirm: "Are you sure you want to delete?" } %>
<% end %>

app/views/tips/new.html.erb
<% content_for :navbar do %>
  <%= render 'shared/gennavbar' %>
<% end %>
<h1>Tips#new</h1>

<%= render 'form'  %>

app/views/tips/show.html.erb
<% content_for :navbar do %>
  <%= render 'shared/gennavbar' %>
<% end %>

<h1>Tips#show</h1>


<h2><%= @tip.subject %></h2>
<p><%= @tip.content %></p>